### ISSUE TITLE
Problem when running script outside of directory containing api file

### ISSUE THREAD

**Issue by mstathers** [mstathers/update-gandi-dns#1]
Currently if you run `update_gandi_dns.pl` from within the directory it and the `gandi_api_key` reside in, the script will work. However, if you change to any other directory, it breaks the relative path filehandle in the script and it will not run:

> Error: No such file or directory

The guilty:

```
open(my $fh, "<", "gandi_api_key")
```

A suggestion by @horgh:

> yea $0 will be './script.pl' or '/home/mike/dir/script.pl'
> so use File::Parse and get the dir part
> er, file::basename maybe

**Comment by rbisewski** [comment]
The above fork resolves this issue. Consider doing a quick test to ensure it works on your end, and then feel free to merge these changes in.
